#pragma once
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <winhttp.h>
#include <bcrypt.h>
#include <shlwapi.h>
#include <shlobj.h>
#include <winver.h>
#include <tlhelp32.h>
#include <shellapi.h>
#include <string>
#include <string_view>
#include <vector>
#include <fstream>
#include <sstream>
#include <cstdio>
#include <cstdarg>
#include <memory>
#include <cstdint>
